--- #YAML:1.0
name:               WWW-Shorten-Bitly
version:            0.78
abstract:           Interface to shortening URLs using L<http:://bit.ly>
author:
    - Pankaj Jain <perl@teknatus.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
