--- #YAML:1.0
name:               WWW-Shorten-Bitly
version:            1.17
abstract:           Interface to shortening URLs using L<http://bitly.com>
author:
    - Pankaj Jain <pjain@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON::Any:     1.18
    Test::More:    0
    WWW::Shorten:  1.9
    XML::Simple:   2.18
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
